### ISSUE TITLE
mode line duplicated after exiting hydra

### ISSUE THREAD

**Issue by nhoffman** [abo-abo/hydra#151]
I've noticed a reproducible artifact in which the mode line is duplicated when I exit a hydra either with a key not represented in the hydra definition, or after an abort with C-g. Here's what I see:

![screen shot 2015-07-25 at 9 31 50 am](https://cloud.githubusercontent.com/assets/440002/8890283/1c699660-32b0-11e5-8c23-0bab8ec27604.png)

I can clear the window-drawing artifact with redraw-display. I see this with all of the hydras I've defined, but here's a representative (though I doubt that the particulars of this hydra have much to do with this bug):

    (if (require 'hydra nil 'noerror)
	(progn
	  (defhydra hydra-launcher (:color blue :columns 4)
	    "hydra-launcher"
	    ("d" insert-date "insert-date")
	    ("D" describe-minor-mode "describe-minor-mode")
	    ("e" save-buffers-kill-emacs "save-buffers-kill-emacs")
	    ("f" fix-frame "fix-frame")
	    ("i" init-edit "init-edit")
	    ("n" my/find-org-index "my/find-org-index")
	    ("N" my/org-index-add-entry "my/org-index-add-entry")
	    ("m" magit-status "magit-status")
	    ("o" copy-region-or-line-other-window "copy-region-or-line-other-window")
	    ("p" package-list-packages "package-list-packages")
	    ("r" redraw-display "redraw-display")
	    ("s" ssh-refresh "ssh-refresh")
	    ("t" org-todo-list "org-todo-list"))

	  (global-set-key (kbd "C-c l") 'hydra-launcher/body))
      (message "** hydra is not installed"))

I'm using hydra-0.13.2, Emacs 24.4.1 (installed from http://emacsformacosx.com) on a mac running Yosemite. I see this issue using the native OS X graphical client (ns) but not in the terminal.

Let me know if I can provide any more detail. Thanks!

**Comment by abo-abo** [comment]
> I'm using hydra-0.13.2, Emacs 24.4.1 (installed from http://emacsformacosx.com) on a mac running Yosemite

Sorry, but I don't have access to OSX. I only have access to GNU/Linux. And I can't reproduce this bug here.  I suggest trying some kind of emacs-snapshot via homebrew - maybe the bug is fixed in Emacs 25.

Otherwise, maybe you or another OSX user could submit a patch. I think the bug conditions could be reduced to just:

```elisp
(defun hydra-bug ()
  (interactive)
  (lv-message "foo")
  (lv-delete-window))
```

The string `"foo"` may be adjusted to reproduce the bug. In that case, it's easier to debug, since the whole `lv` code is only 50 lines.

**Comment by nhoffman** [comment]
Thanks for the response. I'm afraid that the function above does not reproduce the bug. I think that I'll just leave this here in case someone more elisp-savvy than I is able to reproduce and is willing offer a patch. I'll report back on whether the bug persists once I update to emacs 25.

**Comment by zhenwenc** [comment]
Hi @nhoffman , many years later... , I am having the same issue with Emacs 26.1 on OSX. Have you identified the root cause? Many thanks!

**Comment by nhoffman** [comment]
Hi @zhenwenc - no, I never looked much further.  I did find a workaround that you may find useful: call ``redraw-display`` on exit. Here's an example.

```elisp
(defhydra hydra-toggle-mode (:color blue :columns 4 :post (redraw-display))
  "hydra-toggle-mode"
  ("RET" redraw-display "<quit>")
  ("c" csv-mode "csv-mode")
...
  ("y" yaml-mode "yaml-mode"))
```

**Comment by zhenwenc** [comment]
Thanks a lot for the answer @nhoffman ! Much appreciated!
