### ISSUE TITLE
Unrecognized key warnings

### ISSUE THREAD

**Issue by diamond-lizard** [abo-abo/hydra#256]
I can't quite tell why this is happening, but quite often when I'm writing the bindings in a defhydra, I'll get lots of warnings like `"Warning (emacs): Unrecognized key: _q_"`.  What's more, they happen with every single keystroke that I type.  So I might get a dozen of those warnings for any given binding I type.

Is there any way to turn off those warnings?  They are really distracting and don't seem to provide any useful information.

**Comment by diamond-lizard** [comment]
Update:  I have now seen this same warning when I eval a hydra that mentions a key in the docstring that's not bound anywhere in the body.  That is actually a useful warning.  But the behavior described in the original report above is not, and sounds like more of a bug.

**Comment by abo-abo** [comment]
This looks a lot like #255, which was already fixed. Can you confirm that you're using the "fixed" MELPA version?

**Comment by diamond-lizard** [comment]
I install all my packages manually, and don't use any package manager.  I did get the latest hydra and company-mode from git, though, and did a "make clean", "make test" (all 38 tests passed), and "make compile" in the hydra directory, though, and the problem still persists.

I think the problem I'm reporting is very similar to #255, but there is a key difference.  If the test case in #255 is modified to read:
```
  ("s" aaa bbb| ;; type "aaa bbb" --> throws unrecognized key warnings
```
Please note the space between `aaa` and `bbb`.  Without the space, the warnings are not issues.  With the space, the warnings are issued.
